// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS5mzDFaVFWb1DwAQynzyVB8rIm3BsTJU',
    appId: '1:191584548678:web:1684a2b6932f3989bbd747',
    messagingSenderId: '191584548678',
    projectId: 'uber-ola-and-indriver-90f69',
    authDomain: 'uber-ola-and-indriver-90f69.firebaseapp.com',
    databaseURL: 'https://uber-ola-and-indriver-90f69-default-rtdb.firebaseio.com',
    storageBucket: 'uber-ola-and-indriver-90f69.appspot.com',
    measurementId: 'G-6PN6P7Z9ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMv33J_Wnqh00uJHYk58b6614ScnZC4Oc',
    appId: '1:191584548678:android:7f69f002d4e4512bbbd747',
    messagingSenderId: '191584548678',
    projectId: 'uber-ola-and-indriver-90f69',
    databaseURL: 'https://uber-ola-and-indriver-90f69-default-rtdb.firebaseio.com',
    storageBucket: 'uber-ola-and-indriver-90f69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfXVVRdVdvdbMJ2kqmFyisIxrEJcpRyD0',
    appId: '1:191584548678:ios:f8c2fe6352d2350ebbd747',
    messagingSenderId: '191584548678',
    projectId: 'uber-ola-and-indriver-90f69',
    databaseURL: 'https://uber-ola-and-indriver-90f69-default-rtdb.firebaseio.com',
    storageBucket: 'uber-ola-and-indriver-90f69.appspot.com',
    iosClientId: '191584548678-qpeli3l8v2aj1kv5iqdku3pc63d8mrpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cabuserapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfXVVRdVdvdbMJ2kqmFyisIxrEJcpRyD0',
    appId: '1:191584548678:ios:f8c2fe6352d2350ebbd747',
    messagingSenderId: '191584548678',
    projectId: 'uber-ola-and-indriver-90f69',
    databaseURL: 'https://uber-ola-and-indriver-90f69-default-rtdb.firebaseio.com',
    storageBucket: 'uber-ola-and-indriver-90f69.appspot.com',
    iosClientId: '191584548678-qpeli3l8v2aj1kv5iqdku3pc63d8mrpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cabuserapp',
  );
}
